# Generated by Django 5.2.5 on 2025-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
